---
title: "Redirections dans WordPress EPFL"
author: "Dominique Quatravaux"
output:
  html_document:
    df_print: paged
---

```{r include, echo = FALSE, message = FALSE}
if (! exists("redirects")) {
    source("htaccesses.R")
}

library(stringr)
library(forcats)
library(ggplot2)
library(ggtext)
```


```{r redirects_pie, echo = FALSE}
redirects %>% count(wp_env, cmd) %>%
    mutate(rank = rank(-n),
           group = ifelse(rank > 5, "Autres",
                          str_glue("<i>{cmd}</i> dans {wp_env}")),
           dagger = ifelse(wp_env == "inside" & cmd == "RewriteRule", "<sup>†</sup>", "")) %>%
    mutate(.by = group, label = str_glue("{ group } ({ sum(n) }){ dagger }")) %>%
    mutate(label = fct_reorder(label, desc(n))) %>%
    ggplot(aes(x="", y=n, fill=label)) +
    geom_bar(stat="identity", width=1) +
    coord_polar("y", start=0) +
    theme_void() +
    labs(caption="Lignes «utiles» dans les <i>.htaccess</i>",
         fill="Type et environnement",
         y = "") +
    theme(
        legend.text = element_markdown(),
        plot.caption = element_markdown()
    )
```

<sup>†</sup> Après élimination des `RewriteRule`s qui servent à authentifier les accès aux média
